version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:current    

commands:
  restore_yarn:
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache
  save_yarn:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_yarn
      - run:
          command: yarn install --immutable --immutable-cache --check-cache
      - save_yarn
      - run:
          command: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn publish

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
